# Site settings
title: Peter Robinson
description: > # this means to ignore newlines until "baseurl:"
  Blockchain, Crosschain, DeFi, and lots more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://drinkcoffee.github.io" # the base hostname & protocol for your site
twitter_username: drinkcoffee2010
github_username:  drinkcoffee
linkedin_username: peter-robinson-98a0061
telegram_username: drinkcoffee2022
scholar_username: QHvuxTYAAAAJ

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Technical Director & Applied Cryptographer"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""