# Site settings
title: Whatgame Studios
description: > # this means to ignore newlines until "baseurl:"
  Making games that truely mean something
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://whatgamestudios.com" # the base hostname & protocol for your site
twitter_username: 14_numbers
github_username:  whatgamestudios
instagram_username: "14numbers_"
linkedin_username: todo
telegram_username: todo
scholar_username: todo
youtube_username: "@14Numbers"

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Making games that truely mean something"
excerpt_separator: "<!--more-->"

include: .well-known

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""